name: Pull Request Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - id: lint
        name: Lint
        run: npm run lint
      
      - id: typecheck
        name: TypeScript Check
        run: npm run typecheck
      
      - id: test
        name: Run tests
        run: npm test
      
      - id: build
        name: Build
        run: npm run build
      
      - name: Comment PR
        uses: actions/github-script@v7
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            const jobUrl = `https://github.com/${owner}/${repo}/actions/runs/${context.runId}`;
            
            const jobStatus = '${{ job.status }}' === 'success' ? '✅ All tests passed!' : '❌ Some tests failed';
            
            github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body: `## Test Results: ${jobStatus}
              
              [View details](${jobUrl})
              
              ### Summary
              - Lint: ${{ steps.lint.outcome || 'skipped' }}
              - TypeScript: ${{ steps.typecheck.outcome || 'skipped' }}
              - Tests: ${{ steps.test.outcome || 'skipped' }}
              - Build: ${{ steps.build.outcome || 'skipped' }}
              
              _Automated comment from CI workflow_`
            })
